# Generated by Django 4.0.4 on 2022-05-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_hydrant_number_in_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrant',
            name='belonging',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='description',
            field=models.CharField(blank=True, max_length=355),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='distance_front',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='distance_left',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='distance_right',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='note',
            field=models.CharField(blank=True, max_length=355),
        ),
        migrations.AlterField(
            model_name='hydrant',
            name='place_plate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
