# Generated by Django 4.0.4 on 2022-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_hydrant_belonging_alter_hydrant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrant',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
